# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: java-dropwizard-template
  title: Java Plugin Dropwizard and CLI template
  description: Provisions a mini Java Plugin Dropwizard and CLI Appli
spec:
  owner: dev-team
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in some steps
      required:
        - component_id
        - name
        - environment
        - owner
      properties:
        component_id:
          title: Component Uniq Id
          type: string
          description: Provide a uniq component (microservice) id in kebab case
          pattern: '^([A-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        environments:
          title: Deployment Environments
          type: array
          description: The environments where we deploy
          items:
            type: string
            default: feat
            enum:
              - feat
              - fix
              - refacto
              - integ
              - alpha
              - hotfix
              - release
            enumNames:
              - 'feature_xxx branchs - from and to be merged in develop branch'
              - 'fix_xxx branchs - from and to be merged in develop branch'
              - 'refacto_xxx branchs - from and to be merged in develop branch'
              - 'develop branch - uniq integration branch for QA Tests in QA env'
              - 'pre-release version_X.Y.0-alpha branchs - from validated develop branch, for System Major or Minor Versions Tests in PPD'
              - 'hotfix version_x.y.Z branchs - from last version branch, for Rapid System Patch Tests in PPD'
              - 'main branch with release_x.y.z tags - from last validated version or hotfix branch in PROD'
          uniqueItems: true
          ui:widget: checkboxes
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          uid:  ${{parameters.component_id}}
          environements : ${{parameters.environments}}
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.name }}
        repoUrl: github.com?owner=lucilegabriellefievetlacombe-afk&repo=${{parameters.component_id}}
        defaultBranch: 'main'
        protectDefaultBranch: false
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  # some outputs which are saved along with the job for use in the frontend
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}