# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: python-flask-template
  title: Python Plugin Flask and CLI template
  description: Provisions a mini Python Plugin Flask and CLI Appli
spec:
  owner: dev-team
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in some steps
      required:
        - component_id
        - name
        - environments
        - owner
      properties:
        component_id:
          title: Component Uniq Id
          type: string
          description: Provide a uniq component (microservice) id in kebab case
          pattern: '^([A-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        name:
          title: Name
          type: string
          description: Unique User Friendly name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        environments:
          title: Deployment Environments
          type: array
          description: The environments where we deploy
          items:
            type: string
            enum:
              - features_for_develop_branch
              - bugfix_for_develop_branch
              - refactos_for_develop_branch
              - integration_in_develop_branch_for_QA_tests
              - PPD_versions_for_system_tests
              - hotfix_for_PROD
              - PROD
          uniqueItems: false
          ui:widget: checkboxes
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
              
  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{parameters.component_id}}
          app_env: ${{parameters.environment}}
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.component_id }}
        repoUrl: github.com?owner=lucilegabriellefievetlacombe-afk&repo=${{parameters.component_id}}
        protectDefaultBranch: 'main'
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  # some outputs which are saved along with the job for use in the frontend
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}






