# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: python-flask-template
  title: Python Plugin Flask and CLI template
  description: Provisions a mini Python Plugin Flask and CLI Appli
spec:
  owner: dev-team
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in some steps
      required:
        - component_id
        - name
        - environments
        - owner
      properties:
        component_id:
          title: Component Uniq Id
          type: string
          description: Provide a uniq component (microservice) id in kebab case
          pattern: '^([A-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        name:
          title: Name
          type: string
          description: Unique User Friendly name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        environments:
          title: Deployment Environments
          type: array
          description: The environments where we deploy
          items:
            type: string
            default: main
            enum:
              - poc
              - feature
              - fix
              - refacto
              - security
              - ci
              - test
              - dependabot
              - renovate
              - perf
              - chlore
              - develop
              - release
              - hotfix
              - main
            enumNames:
              - 'poc/ruid branchs - for Proof Of Concept (POC), recherche and faisability exploration'  
              - 'feature/ruid branchs - new feature development (from and to be merged in develop branch)'
              - 'fix/ruid branchs - for bug fix (from and to be merged in develop branch)'
              - 'refacto/ruid branchs - for refactoring (from and to be merged in develop branch)'
              - 'security/ruid branchs - for hardening (from and to be merged in develop branch or from alpha release to be merge in release)'
              - 'ci/ruid branchs - for ci cd features and fix (from and to  be merged in develop branch and cherry picked in release branch)'
              - 'test/ruid branchs - for test automation (from and to be merged in develop branch)' 
              - 'dependabot - Bot automated dependencies updates'
              - 'renovate - Bot automated project source updates'
              - 'perf - for optimization tunning (from and to be merged in develop branch or from alpha release to be merge in release)'
              - 'chlore - for dependencies updates (from and to be merged in develop branch)'
              - 'develop uniq integration branch - for QA Acceptance Tests in QAL env (merge targed, except hotfix and late hardening or late tunning'
              - 'pre-release/X.Y-alpha branchs - (from validated develop branch, for System Major or Minor Versions Tests in PPD, to be merged and tagged in main)'
              - 'hotfix/x.y.Z branchs - for Rapid System Tests in PPD after hotfix (from last version branch, to be merged and tagged in main)'
              - 'main uniq production branch -  with release_x.y.z tags - from last validated version or hotfix branch in PROD'
          uniqueItems: true
          ui:widget: checkboxes
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
              
  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          uid:  ${{parameters.component_id}}
          environements : ${{parameters.environments}}
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.name }}
        repoUrl: github.com?owner=luspokvenus&repo=${{parameters.component_id}}
        defaultBranch: 'main'
        protectDefaultBranch: false
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  # some outputs which are saved along with the job for use in the frontend
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}










